services:
  - type: web
    name: telegram-esport-bot
    env: python
    plan: free
    buildCommand: python3.11 -m pip install -r requirements.txt
    startCommand: python3.11 bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false